### ISSUE TITLE
URI settings in connect-mongodb-session module.

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [mongodb-js/connect-mongodb-session#13]
I have little bit confusion about the following code.

```var store = new MongoDBStore(
      {
        uri: 'mongodb://localhost:27017/connect_mongodb_session_test',
        collection: 'mySessions'
      });```
From the above code what should be the URI setting.I am running my MongoDb in local host.I can not understand about the last text after '/'(``i.e-connect_mongodb_session_test``).Please help me to set uri in my local system.

**Comment by vkarpov15** [comment]
The URI is a [mongodb connection string](http://docs.mongodb.org/manual/reference/connection-string/). The text after the '/' is the database name.

**Comment by subhrajyotiw5rtc** [comment]
I want to know is this `connect_mongodb_session_test` fixed or not ?

**Comment by vkarpov15** [comment]
Wouldn't be much of a configurable option if it was fixed. You can use whatever database name you want.

**Comment by subhrajyotiw5rtc** [comment]
Ok,I set the URI but when i tried to run the server i got the following error.

Error:

```
     process.nextTick(function() { throw err; })
                                            ^
Error: Error connecting to db: connect Unknown system errno 10042
    at C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb-session\index.js:
45:17
    at C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb-session\node_modu
les\mongodb\lib\mongo_client.js:236:20
    at C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb-session\node_modu
les\mongodb\lib\db.js:203:14
    at null.<anonymous> (C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb
-session\node_modules\mongodb\lib\server.js:226:9)
    at g (events.js:180:16)
    at emit (events.js:98:17)
    at null.<anonymous> (C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb
-session\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js
:255:68)
    at g (events.js:180:16)
    at emit (events.js:98:17)
    at null.<anonymous> (C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb
-session\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:7
7:12)
```
And the following is my server.js file.

```
var port=8888;
var express=require('express');
var http=require('http');
var morgan         = require('morgan');
var bodyParser     = require('body-parser');
var methodOverride = require('method-override');
var cookieParser     = require('cookie-parser');
var session = require('express-session');
var MongoDBStore = require('connect-mongodb-session')(session);
var mongo = require('mongojs');
var app=express();
var server=http.createServer(app);
db = 'doctor',
collections = ['oditek'],
db = mongo("127.0.0.1:27017/"+db, collections);
app.use(express.static(__dirname + '/public'));     // set the static files location /public/img will be /img for users
app.use(morgan('dev'));                     // log every request to the console
app.use(bodyParser.urlencoded({ extended: false }))    // parse application/x-www-form-urlencoded
app.use(bodyParser.json())    // parse application/json
app.use(methodOverride());
app.use(cookieParser());                 // simulate DELETE and PUT
var store = new MongoDBStore(
      { 
        uri: 'mongodb://127.0.0.1:27017/doctor',
        collection: collections
      });
app.use(require('express-session')({
      secret: 'This is a secret',
      cookie: {
        maxAge: 1000 * 60 * 60 * 24 * 7 // 1 week 
      },
      store: store
    }));
app.get('/',function(req,res){
	res.sendfile('view/index.html');
})
app.get('/login',function(req,res){
	res.sendfile('view/login.html');
});
app.get('/chatroom',function(req,res){
	if(req.session){
		res.sendfile('view/chatroom.html');
	}
});
app.post('/signUp',function(req,res){
	req.session.name=req.body.username;
	db.oditek.insert({username:req.body.username,email:req.body.useremail,password:req.body.userpass},function(err,docs){
		if(docs){
			res.send(docs);
		}
	});
});
server.listen(port);
console.log('server is running on the port'+port);
```

Kindly  help me to resolve this error.

**Comment by vkarpov15** [comment]
Which version of Windows are you using? Also, does the mongojs connection work?

**Comment by imlucas** [comment]
@vkarpov15 looks like that server error code maps to `10042 code return of $key has to be an object` https://github.com/mongodb/mongo/blob/845a2dcc23a597520065d1258089cc87dabf6cb8/docs/errors.md#srcmongodbcommandsgroupcpp

**Comment by vkarpov15** [comment]
@imlucas I don't think that's the case because this module doesn't use the `group()` function at all. My current hypothesis is that this is a [windows socket error code 10042 WSAENOPROTOOPT](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx)

**Comment by imlucas** [comment]
@vkarpov15 oh nice!  figured it was a long shot.

Looking back at code above, another smell perhaps you could put down as well: collection passed to MongoStore is an array

**Comment by vkarpov15** [comment]
Good catch @imlucas ! @subhrajyotiw5rtc try:

```javascript
var store = new MongoDBStore(
      { 
        uri: 'mongodb://127.0.0.1:27017/doctor',
        collection: collections[0]
      });
```

connect-mongodb-session expects `collection` to be a string, not an array. See if that helps.

**Comment by imlucas** [comment]
:high_five:

**Comment by imlucas** [comment]
@vkarpov15 speaking of, remind me to bug you more about using [ampersand-state](http://ampersandjs.com/docs#ampersand-state) for options objects that allow better guarantees for runtime type safety (eg above would have just thrown a TypeError), documenting defaults, etc.

**Comment by vkarpov15** [comment]
Looks like an interesting tool. I'll investigate more - might be worth just switching over to TypeScript if I'm gonna go that route :)

**Comment by imlucas** [comment]
eh ampersand-state is nice because it's so lightweight and doesn't involve compilation

**Comment by subhrajyotiw5rtc** [comment]
@vkarpov15 : I am using windows-xp and mongojs is also working alone.When i added MongoDBStore this type of error came.

**Comment by subhrajyotiw5rtc** [comment]
I tried by passing collections as an array but same error.

**Comment by vkarpov15** [comment]
The point is **don't** pass an array to the `collection` argument, but a **string**.

Also, can you try doing `npm install mongodb@2.0.33` and running the following code:

```javascript
var mongodb = require('mongodb');
mongodb.MongoClient.connect('mongodb://127.0.0.1:27017/doctor', function(error, db) {
  console.log('Error: ' + error;
  process.exit(0);
});
```

This will allow us to bisect whether this is an issue with the mongodb driver or if there's something going wrong with connect-mongodb-session.

**Comment by subhrajyotiw5rtc** [comment]
@vkarpov15  ,If i am using mongoJS  for mongodb it is working fine but i need to store the session at the time of user login.For that i used ```connect-mongodb-session``` and after adding this i got this type of error.Please let me to know Is mongojs not suitable with connect-mongodb-session module so that i will move to other driver.

**Comment by vkarpov15** [comment]
It should be suitable, there's no reason why having mongojs installed as a peer dependency should prevent this module from working. The reason why I'm asking you to try installing the mongodb driver is that connect-mongodb-session uses the mongodb driver under the hood. Therefore, if you run the above code and it succeeds, we'll know that something's off with connect-mongodb-session, whereas if the code fails we'll know that there's a potential issue with the driver.

**Comment by vkarpov15** [comment]
No activity for a while, closing this. Re-open if this is still an issue.
