### ISSUE TITLE
Getting error while installing ```connect-mongodb-session```.

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [mongodb-js/connect-mongodb-session#14]
Hi,I am getting the following error when i tries to install this module as ``` npm install connect-mongodb-session```.

Error:
```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\
\xampp\\htdocs\\odiya_chat\\node_modules\\connect-mongodb-session\\node_modules\
\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext
\\build\\Release\\bson.node" "--module_name=bson" "--module_path=C:\\xampp\\htdo
cs\\odiya_chat\\node_modules\\connect-mongodb-session\\node_modules\\mongodb\\no
de_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\build\\Rel
ease"
gyp ERR! cwd C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb-session\nod
e_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-
ext
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb-se
ssion\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modu
les\bson-ext\build\Release\bson.node --module_name=bson --module_path=C:\xampp\h
tdocs\odiya_chat\node_modules\connect-mongodb-session\node_modules\mongodb\node_
modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\xampp\htdocs\odiya_c
hat\node_modules\connect-mongodb-session\node_modules\mongodb\node_modules\mongo
db-core\node_modules\bson\node_modules\bson-ext\node_modules\node-pre-gyp\lib\ut
il\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:833:5)
node-pre-gyp ERR! System Windows_NT 5.1.2600
node-pre-gyp ERR! command "node" "C:\\xampp\\htdocs\\odiya_chat\\node_modules\\c
onnect-mongodb-session\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_
modules\\bson\\node_modules\\bson-ext\\node_modules\\node-pre-gyp\\bin\\node-pre
-gyp.js" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\xampp\htdocs\odiya_chat\node_modules\connect-mongodb-se
ssion\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modu
les\bson-ext
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok

```
I have also added the ```"connect-mongodb-session": "~1.0.2"``` in my pachage.json file.
Please help me to resolve this error and install this module successfully.

**Comment by vkarpov15** [comment]
As far as I can tell that's just a warning, not an error. If node-pre-gyp fails, that just means you'll be using the native BSON parser, which is ok. There's numerous suggestions for this issue at Automattic/mongoose#2285
