### ISSUE TITLE
E11000 duplicate key error collection

### ISSUE THREAD

**Issue by vealjoshua** [mongodb-js/connect-mongodb-session#72]
`E11000 duplicate key error collection: 5c70c028c56c980b9d1eeb65_freecog.sessions index: _id_ dup key: { : "fWOQ_VluVcC2ps4G28GnCpqtF3khaS3W" }`

I'm getting this error when trying to log in for my user twice.

**Comment by vealjoshua** [comment]
`at /var/app/current/node_modules/connect-mongodb-session/index.js:226:21
    at err (/var/app/current/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:411:14)
    at session.endSession (/var/app/current/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:397:27)
    at ClientSession.endSession (/var/app/current/node_modules/mongodb-core/lib/sessions.js:134:41)
    at executeCallback (/var/app/current/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:395:17)
    at updateCallback (/var/app/current/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/collection_ops.js:1402:19)
    at updateDocuments (/var/app/current/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/collection_ops.js:1502:62)
    at handleCallback (/var/app/current/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:128:55)
    at coll.s.topology.update (/var/app/current/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/collection_ops.js:1465:14)
    at handler (/var/app/current/node_modules/mongodb-core/lib/topologies/replset.js:1155:22)`
