### ISSUE TITLE
Error setting new cookie 

### ISSUE THREAD

**Issue by oOBlinkOo** [mongodb-js/connect-mongodb-session#78]
Hello Im having this error, any info about this?
```
Error: Error setting nOomfHkFjg9PUyGVQK77Q4q1yWqSfCfy to Session {
  cookie:
   { path: '/',
     _expires: 2020-02-12T14:58:30.224Z,
     originalMaxAge: 604800000,
     httpOnly: true } }: failed to reconnect after 30 attempts with interval 1000 ms
    at /usr/src/app/node_modules/connect-mongodb-session/index.js:226:21
    at executeCallback (/usr/src/app/node_modules/mongodb/lib/operations/execute_operation.js:74:5)
    at updateCallback (/usr/src/app/node_modules/mongodb/lib/operations/update_one.js:30:19)
    at updateDocuments (/usr/src/app/node_modules/mongodb/lib/operations/update_one.js:24:64)
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:128:55)
    at Object.coll.s.topology.update [as c] (/usr/src/app/node_modules/mongodb/lib/operations/common_functions.js:372:21)
    at Store.flush (/usr/src/app/node_modules/mongodb/lib/topologies/topology_base.js:114:8)
    at Server.reconnectFailedHandler (/usr/src/app/node_modules/mongodb/lib/topologies/server.js:257:20)
    at Server.emit (events.js:198:13)
    at Server.EventEmitter.emit (domain.js:448:20)
    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/topologies/server.js:420:14)
    at Pool.emit (events.js:198:13)
    at Pool.EventEmitter.emit (domain.js:448:20)
    at Timeout.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:325:12)
    at ontimeout (timers.js:436:11)
```

**Comment by wfjake** [comment]
> `failed to reconnect after 30 attempts with interval 1000 ms`

This is because the connection between MongoDB and your app has been lost. Perhaps the server went down or something went wrong in the network.

> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

This is a separate issue. You probably have a middleware running before `request.session()` which uses .send() or similar which caused the response to already be sent. Basically, it is erroring because you are trying to modify a response which the browser already received.
